language: node_js
notifications:
  email: false
node_js: 8
script:
  - npm test
  - npm run build
after_success:
  - npm run send-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/